### PR TITLE
Icons for all the packs

### PR DESCRIPTION
**Pull request by emedvedev**

### CODE REVIEW

**Comment by jfryman** [comment]
vqgemsr

**Comment by manasdk** [comment]
Nice!

**Comment by Kami** [comment]
Nice, indeed.

To be on the safe side we should probably add a similar "disclaimer" to the README.md  - "StackStorm and the StackStorm project logo are trademarks of the StackStorm, Inc. All other marks mentioned or displayed may be trademarks or registered trademarks of their respective owners."

Later one I will also update the script which generates README.md to include the icons there.

**Comment by Kami** [comment]
Thanks. I've merged this.

I will create a separate PR for readme changes.

**Comment by Kami** [comment]
Icons are now also displayed in the README - https://github.com/StackStorm/st2contrib

**Comment by lakshmi-kannan** [comment]
Holy jolly!

**Comment by jfryman** [comment]
@Kami very nice!

Have some goats.

rdcl

**Pull request merged**
