### PR TITLE
Basic updates to make handler work with https

### PR DESCRIPTION
**Pull request by manasdk**

### CODE REVIEW

**Comment by Kami** [comment]
IIRC, we have a similar script lying around somewhere?

Or, maybe I'm mixing things up.

**Comment by Kami** [comment]
Now that we have a test framework in place we should also add some tests for this script since it always gets out of date or it's broken.

**Comment by manasdk** [comment]
> IIRC, we have a similar script lying around somewhere?

Isn't this the script?

**Comment by manasdk** [comment]
> Now that we have a test framework in place we should also add some tests for this script since it always gets out of date or it's broken.

Needs integration tested against a full stackstorm install. Is that possible or only unit testing?

**Comment by DoriftoShoes** [comment]
So this looks good but when did we make the single port change?  Are the old URLs still in any currently supported versions?

**Comment by manasdk** [comment]
The single port change went in v1.2. I don't thing old URLs are supported any longer

**Comment by manasdk** [comment]
> I don't thing old URLs are supported any longer

This is an installer choice though so you need depends on the configuration.

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/support/p1454967684000368

**Pull request merged**
