### PR TITLE
Open ports

### PR DESCRIPTION
**Pull request by Aamir-raza-1**
added action description in readme file

### CODE REVIEW

**Comment by jfryman** [comment]
@Aamir-raza-1 could you rebase and repush? Looks like there is a merge conflict. Otherwise, :+1:

**Comment by Kami** [comment]
Yeah, what james said. Besides that, LGTM.

**Comment by Aamir-raza-1** [comment]
Yeah sure, but when I `git-rebase open_ports` or give a tag it says `Current branch open_ports is up to date.`
Then I forced rebase giving flag `-f`  and it said 

`Current branch open_ports is up to date, rebase forced.
First, rewinding head to replay your work on top of it...
Fast-forwarded open_ports to open_ports.`

so git status tell me working directory is clean.

**Comment by Kami** [comment]
Closing since this has already been fixed and it's not relevant anymore. Thanks.

**Pull request closed without merging**
