### PR TITLE
Add new actions and workflow to Orion pack

### PR DESCRIPTION
**Pull request by jjm**
### Status 

- pack extension, work in progress
- bugfix

### Description

Add new actions, a workflow to move nodes between pollers (and any that go down back), plus a few bug fixes.

### Checklist (tick everything that applies)

- [x] Metadata: pack.yaml, icon, structure (required for new packs)
- [X] Version bump (required for changed packs)
- [x] Code linting (required, can be done after the PR checks)
- [x] [Tests](https://docs.stackstorm.com/development/pack_testing.html) (not required but really recommended)
- [x] Update for new v1.5 features (e.g. config.schema).

### CODE REVIEW

**Comment by lakshmi-kannan** [comment]
LGTM. Since we don't have branches and this repo shares multiple packs, having an ``in development`` pack makes little sense. Once we move to repo per pack, this should become easier. And sorry for the delay in review.

**Comment by jjm** [comment]
Sorry I've been side tracked a little, the main thing I need to finish is the migration to config.schema and clean up the new workflow.

**Comment by jjm** [comment]
I've had the time to get this sorted and get it migrated to a schema approach. The tests should pass and I'll do some manual checks this afternoon after which it should be good to merge.

**Comment by jjm** [comment]
I don't understand what the failed check about is :-( the pack loads ok on my dev system.

**Pull request merged**
