### PR TITLE
Remove sudo parameter from all the local runner actions

### PR DESCRIPTION
**Pull request by Kami**
This pull request sudo parameter from all the local runner actions to account for this runner parameter removal in https://github.com/StackStorm/st2/pull/2671.

Note: those changes are fully backward compatible so we can merge them before we merge https://github.com/StackStorm/st2/pull/2671.

### CODE REVIEW

**Comment by Kami** [comment]
Looks like packagecloud actions use sudo and default it to true. Is this required aka things will break if I remove it?

/cc @DoriftoShoes

**Comment by Kami** [comment]
Looks like there are two blockers right now - ansible and packagecloud actions.

For packagecloud I think we can probably just get rid of it, but for ansible we need to verify that it still works without sudo (I would imagine, this could cause issues since it might not be able to access inventory file, etc.).

**Comment by lakshmi-kannan** [comment]
lgtm

**Comment by lakshmi-kannan** [comment]
You kind have a nervous +1 from @armab to deprecate sudo in ansible pack. Internal slack link: https://stackstorm.slack.com/archives/standup/p1462455873001277 (No public access)

**Comment by DoriftoShoes** [comment]
I don't remember why packagecloud uses it.  We just need to make sure the system user has the packagecloud cli set up...then it should work fine.  I am +1 to this change.

**Comment by armab** [comment]
Related to: https://github.com/StackStorm/st2contrib/issues/363

**Comment by Kami** [comment]
@DoriftoShoes Thanks for confirming.

As far as ansible pack goes - I will look into it (I will try to test it) and I will also update the readme and changelog and clarify this change and potential impact.

**Comment by Kami** [comment]
Closing for now.

Sadly this requires more work.

**Pull request closed without merging**
