### PR TITLE
first implementation of multipart message handling

### LINKED ISSUE #254: packs/email imap-sensor not handling multipart mime messages
the email pack has a problem with multipart mime messages. upon hitting a multipart message it crashes with "Can't decorde message body: DecodeError(TypeError(......"

_process_message() already parses mime for the headers. instead of body = message.body it should be something like "body=mime_msg.body". then it would only be parsed if *not* multipart.

### PR DESCRIPTION
**Pull request by nido009**
Fixes #254.

### CODE REVIEW

**Comment by Kami** [comment]
I thought this was fixed as part of #244, but it looks like it wasn't. Good catch and thanks.

I will have a better look and test it later.

**Comment by nido009** [comment]
well, it does not fix #254 enterierly, it just improofes it. i will comment on the issue and try to adapt the pullrequest

**Comment by Kami** [comment]
@nido009 Yeah, I just updated the description to reference the ticket number so it's more clear what this PR is for.

**Comment by Kami** [comment]
@nido009 Is this still relevant after #257 has been merged or it can be closed now?

**Comment by Kami** [comment]
Closing since #257 resolved this.

Thanks anyway!

**Pull request closed without merging**
