### PR TITLE
Change params type from list to array

### PR DESCRIPTION
**Pull request by LindsayHill**
### Status 

- bugfix

### Description

Bug fix  - incorrect parameter type

### Checklist (tick everything that applies)

- [ ] Metadata: pack.yaml, icon, structure (required for new packs)
- [ X] Version bump (required for changed packs)
- [ ] Code linting (required, can be done after the PR checks)
- [ ] [Tests](https://docs.stackstorm.com/development/pack_testing.html) (not required but really recommended)

### CODE REVIEW

**Comment by lakshmi-kannan** [comment]
Good catch!

**Comment by Kami** [comment]
Good catch :+1: 

Not sure how the tests didn't originally catch it though...

**Comment by LindsayHill** [comment]
@Kami I've been wondering about the tests too. Even if we don't pick it up when the tests run, I think it should be picked up when you attempt to register that action. From what I could tell, it lets you register the action, but doesn't fail until you try to use it.

**Comment by Kami** [comment]
Ah, that's weird, indeed - registering a resource should indeed fail on invalid schema (invalid parameter type as in this case).

In any case, it's possible it's some edge case we don't handle correctly, will dig in at some point.

**Comment by LindsayHill** [comment]
@Kami I just did a quick re-check with 1.6.0-4 (my original tests were with 1.5). Looks like it still allows registration of an invalid parameter type. 
I _suspect_ (but haven't tested) that if I used the new config schema it would fail.

**Comment by Kami** [comment]
I was able to replicate the problem, I will look into a possible fix.

**Comment by Kami** [comment]
@LindsayHill This was good catch, it looks like we never actually validated `type` attribute for action parameters correctly.

I have a fix in place and will add test to make sure this doesn't happen again in the future.

**Comment by LindsayHill** [comment]
Excellent. I'm sure the fix will help someone in future

**Pull request merged**
