### PR TITLE
hpe_icsp migrate to config.schema

### PR DESCRIPTION
**Pull request by LindsayHill**
### Status 

- pack extension, complete

### Description

Migrate hpe_icsp to `config.schema.yaml`

### Checklist (tick everything that applies)

- [X] Metadata: pack.yaml, icon, structure (required for new packs)
- [X] Version bump (required for changed packs)
- [X] Code linting (required, can be done after the PR checks)
- [ ] [Tests](https://docs.stackstorm.com/development/pack_testing.html) (not required but really recommended)

### CODE REVIEW

**Comment by LindsayHill** [comment]
@paul-mulvihill - Thanks for the change in #619 - I've further updated it to move to `config.schema.yaml`

**Comment by LindsayHill** [comment]
Hmm, looks like the new pack checks weren't run on my local box. Will need to check my local setup and fix these issues

**Comment by Kami** [comment]
It looks like you just need to update the sample config and specify sample values of the right type for all the required config options.

**Comment by LindsayHill** [comment]
Yep, looks that way. Trying to work out why my local system complaining
about missing imports when running make configs-check. Part of the problem
is working on the train with intermittent connectivity.

Will fix it when I get to the office

**Comment by Kami** [comment]
Yeah - you need latest changes from st2 repo and st2sdk for the make targets to work - running make configs-check should indeed pull down those dependencies but yeah, bad connectivity could cause issues.

**Comment by LindsayHill** [comment]
And now tests pass...had to do some manual imports on my local system to run checks locally. Not too worried about that right now though.

**Comment by Kami** [comment]
LGTM :+1:

**Pull request merged**
