### PR TITLE
Wit.ai Integration

### PR DESCRIPTION
**Pull request by jfryman**
Turns out, it's simple enough. This PR adds support for `wit.ai` to StackStorm.

## Actions

* `text_query` - Send a text based query to wit.ai

### CODE REVIEW

**Comment by Kami** [comment]
LGTM, +1

**Comment by manasdk** [comment]
Out of curiosity what does the response look like?

**Comment by manasdk** [comment]
+1

**Comment by Kami** [comment]
@manasdk Looks like something like that - https://wit.ai/docs/http/20141022#get-intent-via-text-link :)

**Comment by jfryman** [comment]
@manasdk the response is sort of gnarly. But, it's doable.

```
---
name: "steve_nlp_to_slack"
pack: "frymanio"
description: "NLP queries sent to Wit.ai/Steve are sent to slack"
enabled: true
trigger:
  type: "core.st2.generic.actiontrigger"
criteria:
  trigger.action_name:
    type: "equals"
    pattern: "witai.text_query"
  trigger.status:
    type: "equals"
    pattern: "succeeded"
  trigger.parameters.text:
    type: "matchregex"
    pattern: "^(steve|<@U03JSQUBD>)"
action:
  ref: "hubot.post_message"
  parameters:
    channel: "#witai"
    message: "Input: {{trigger.result.result._text}}\n\nTop Outcome ({{trigger.result.result.outcomes[0].confidence}}): {{trigger.result.result.outcomes[0].intent}}\nEntities: {{trigger.result.result.outcomes[0].entities}}"
```

**Comment by jfryman** [comment]
```[{u'entities': {u'on_off': [{u'value': u'off'}]}, u'confidence': 0.855, u'intent': u'control_lights', u'_text': u'steve: turn off the light'}]```

**Pull request merged**
