### PR TITLE
Correct a reference of `Travis` to `Circle` in Circle CI pack.

### PR DESCRIPTION
**Pull request by jjm**
### Status 

- bugfix.
- Complete.

### Description

Correct a typo in the README (so not increasing the pack version number).

### Checklist (tick everything that applies)

Correct a typo in the Circle CI README.md.

### CODE REVIEW

**Comment by jvrplmlmn** [comment]
👍

**Comment by jjm** [comment]
Oh dear, I'll see if I can fix that unit test as well.

**Comment by Kami** [comment]
Good catch, thanks.

**Comment by Kami** [comment]
Looks like the error is related to new version of requests, we encountered the same issue in StackStorm.

With new version, every header value sent via `requests` now needs to be a string. I will merge this directly into master and make the headers change myself (there are probably other places which need to be fixed / changed as well).

**Comment by Kami** [comment]
There we go - 80f05c70a8039c5b613146dcb0c05468d9dcbfb0.

It's actually quite a nasty change in requests, I would imagine it affects a lot of the existing code and it's likely new version of requests will change to the old behavior in the future.

**Comment by jjm** [comment]
Thanks @Kami

**Pull request merged**
