### PR TITLE
Since classname == sensor.name cannot have multiple clashing class na…

### PR DESCRIPTION
**Pull request by manasdk**
### Description

Pack fixes newrelic sensor name

### Checklist (tick everything that applies)

- [x] Version bump (required for changed packs)
- [x] Code linting (required, can be done after the PR checks)
- [x] Tests (not required but really recommended)

### CODE REVIEW

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1457122143006204

**Comment by lakshmi-kannan** [comment]
@Kami Fat finger :P

**Comment by lakshmi-kannan** [comment]
lgtm

**Comment by Kami** [comment]
Good catch.

**Pull request merged**
