### PR TITLE
added feature that allows the git sensor to monitor a branch

### PR DESCRIPTION
**Pull request by ErikThoreson**
### Status 

Replace this: describe the pack and PR status. Examples: 

- added small feature 
- ready for review

### Description

Added feature that allows the git integration pack to monitor a branch of a repo.

### Checklist (tick everything that applies)

- [ ] Metadata: pack.yaml, icon, structure (required for new packs)
- [x] Version bump (required for changed packs)
- [x] Code linting (required, can be done after the PR checks)
- [ ] [Tests](https://docs.stackstorm.com/development/pack_testing.html) (not required but really recommended)

### CODE REVIEW

**Comment by Kami** [comment]
Thanks.

The change looks good to me.

Just to verify how it worked in the past / before - did it monitor all the branches or just master?

**Comment by ErikThoreson** [comment]
Right. It just monitored the master without passing in args to the clone_from method used by GitPython

**Comment by ErikThoreson** [comment]
@Kami any more thoughts on this one?

**Comment by Kami** [comment]
@ErikThoreson Looks good, merged into master. Thanks!

**Pull request merged**
