### PR TITLE
 change vpc_security_groups type to array

### PR DESCRIPTION
**Pull request by pidah**
### Status 

Replace this: describe the pack and PR status. Examples: 
- bugfix

### Description

vpc_security_groups is of type list: https://github.com/boto/boto/blob/dd5f87c7d5c55b69aa23bb4c21010897eb0deb42/boto/rds/dbinstance.py#L378-L379
### Checklist (tick everything that applies)

- [x] Metadata: pack.yaml, icon, structure (required for new packs)
- [x] Version bump (required for changed packs)
- [x] Code linting (required, can be done after the PR checks)
- [ ] [Tests](https://docs.stackstorm.com/development/pack_testing.html) (not required but really recommended)

### CODE REVIEW

**Comment by Kami** [comment]
Thanks.

The changes LGTM, but I'm just worried they will get overwritten by the auto-generator script the next time it's ran.

**Comment by Kami** [comment]
Merged, thanks.

/cc @DoriftoShoes @manasdk can one of you confirm that this won't get overriden next time re-generate script is run (or if it would, can we add an override or something)?

**Comment by pidah** [comment]
@Kami can you point met to the auto-generator script ?

**Comment by Kami** [comment]
@pidah Honestly I can't find it right now. Best to wait on @DoriftoShoes :)

**Comment by pidah** [comment]
@kaml 👍

**Pull request merged**
