### PR TITLE
Aws elb

### PR DESCRIPTION
**Pull request by amith23**
### Status 

Replace this: describe the pack and PR status. Examples: 

- pack extension, work in progress

### Description

Actions for managing  aws ELB functions were missing on the aws pack. This pull request contain elb related actions.

### Checklist (tick everything that applies)

- [ ] Metadata: pack.yaml, icon, structure (required for new packs)
- [x] Version bump (required for changed packs)
- [x] Code linting (required, can be done after the PR checks)
- [x] [Tests](https://docs.stackstorm.com/development/pack_testing.html) (not required but really recommended)

### CODE REVIEW

**Comment by amith23** [comment]
AWS elb related actions for AWS pack

**Comment by LindsayHill** [comment]
This looks really good! We've recently made some major changes to our pack management, and moved all our packs to the StackStorm Exchange. Each pack now has its own repository. Could you open this PR against https://github.com/StackStorm-Exchange/stackstorm-aws
Thanks!

**Comment by amith23** [comment]
sure I'll PR to given repo

**Comment by LindsayHill** [comment]
See https://github.com/StackStorm-Exchange/stackstorm-aws/pull/6

**Pull request closed without merging**
