### PR TITLE
Windows pack

### PR DESCRIPTION
**Pull request by Kami**
First implementation includes `wmi_query` action.

### CODE REVIEW

**Comment by Kami** [comment]
The same action / information would also be useful in the sensor context. There are more actions like that and we should think about it and try to come up with some convention / pattern for handling that.

A simple solution would be to also implement a sensor which emits this information, but this results in a duplicated code, etc.

**Comment by manasdk** [comment]
Wouldn't it be better to have a native windows runner that access native win32 APIs?

**Comment by Kami** [comment]
@manasdk Well, this uses WMI (https://msdn.microsoft.com/en-us/library/aa384642%28v=vs.85%29.aspx) which is a native Windows thing. Among other things, WMI can also be accessed remotely from a host which has a client (either Windows or Linux).

So in short - unless we need to support really old Windows server version, it doesn't matter since WMI appears to be the future of (remote) data retrieval and management.

**Comment by dzimine** [comment]
This is really cool. 

As a follow up, think about making it a runner - not necessarily windows runner, but a "normal" runner. And what would it take to convert it to the powershell runner?

**Comment by Kami** [comment]
@dzimine I added some comments about my findings to the JIRA ticket (STORM-973).

We could make it a runner and get it to execute console and powershell commands using `winexe` which works on Linux. The problem with winexe is that latest stable version has some bugs and we would need to use a version from master. This means we would need to build a version for distros we support which is something we could ideally avoid.

**Comment by manasdk** [comment]
There is no way we get proper windows integration without having a runner that executes on windows. I see this as a windows management pack. Can we say a windows runner is different from this pack?

**Comment by manasdk** [comment]
After understanding the intergation point I am positive about this pack. We should limit/define its scope.

**Comment by Kami** [comment]
I will get this merged now, but eventually this action should be made obsolete in favor of https://github.com/StackStorm/st2/pull/1287

**Pull request merged**
