### PR TITLE
Change AND to OR in the Twitter sensor

### PR DESCRIPTION
**Pull request by emedvedev**
Does exactly what it says.

### CODE REVIEW

**Comment by Kami** [comment]
This works for me, although it's also possible to achieve the same behavior using OR directly in the keyword.

For example:

```yaml
- StackStorm OR Stack_Storm
```

**Comment by Kami** [comment]
And no matter which approach we decide to go with, it would be good to document this with some examples in the readme :)

**Comment by emedvedev** [comment]
> This works for me, although it's also possible to achieve the same behavior using OR directly in the keyword.

Surprisingly, it's not. I looked at the code, and I thought it should be like that, too, but that didn't work.

**Comment by Kami** [comment]
@emedvedev I should have been more clear, should have said "it's possible to achieve the same behavior if you use a single search operator" :)

In fact, that's how the pack worked at the beginning - it only took a string, then at some point we updated it to take a list / array. But yeah, when we updated it to take a list it would make more sense to also change it to OR behavior by default, agreed :)

**Comment by Kami** [comment]
:+1:

**Comment by emedvedev** [comment]
Updated the readme and default config, too.

**Pull request merged**
