### PR TITLE
Move linux pack

### PR DESCRIPTION
**Pull request by dzimine**
Linux pack is promoted to st2, moving to StackStorm/st2 repo.

Merge after https://github.com/StackStorm/st2/pull/1134 is merged, tested and validated.

### CODE REVIEW

**Comment by DoriftoShoes** [comment]
+1

**Comment by Kami** [comment]
We should at least add / leave linux directory with README.md which says that this pack has been promoted to the st2 repo and is included with default installations of StackStorm >= 0.8

**Comment by Kami** [comment]
59c8043be35963f37e12c70919c9f58211ce1edd

**Comment by dzimine** [comment]
Let’s do it once decide that we keep Linux. Sun EOD.

**Pull request merged**
