### PR TITLE
python cannot find module bucket without the full path to Bucket

### PR DESCRIPTION
**Pull request by ErikThoreson**
### Status 

Replace this: describe the pack and PR status. Examples: 

- bugfix

### Description

Python 2.7 cannot import the s3.bucket module. Must import the entire path. s3.bucket.Bucket

### Checklist (tick everything that applies)

- [ ] Metadata: pack.yaml, icon, structure (required for new packs)
- [x] Version bump (required for changed packs)
- [x] Code linting (required, can be done after the PR checks)
- [ ] [Tests](https://docs.stackstorm.com/development/pack_testing.html) (not required but really recommended)

### CODE REVIEW

**Comment by emedvedev** [comment]
Thanks for the PR! After the 2.1 release, st2contrib is closed for contributions (https://github.com/stackstorm/st2contrib#we-are-moving), but it would be really great if you could open the PR against https://github.com/StackStorm-Exchange/stackstorm-aws.

You can find more information in the docs: https://docs.stackstorm.com/reference/pack_management_transition.html

**Comment by ErikThoreson** [comment]
Hello, Here is the exception I'm receiving when running the aws.ec2_create_tags action.

bash-4.2$ st2 run aws.ec2_create_tags resource_ids=ami-ff5df69f tags="securitytests=test"exit
..
id: 584b35f52b71111ccc7144eb
status: failed
parameters: 
  resource_ids: ami-ff5df69f
  tags: securitytests=testexit
result: 
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py", line 211, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py", line 126, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/aws/actions/run.py", line 20, in run
    return self.do_method(module_path, cls, action, **kwargs)
  File "/opt/stackstorm/packs/aws/actions/lib/action.py", line 122, in do_method
    formatted = self.resultsets.formatter(resultset)
  File "/opt/stackstorm/packs/aws/actions/lib/ec2parsers.py", line 203, in formatter
    return self.selector(output)
  File "/opt/stackstorm/packs/aws/actions/lib/ec2parsers.py", line 192, in selector
    elif isinstance(output, s3.bucket.Bucket):
AttributeError: 'module' object has no attribute 'bucket'


If I try to help(s3.bucket) with both 2.41 or newer event as a standalone action I'll receive the same error as well as another of my co-worders.

Thanks for the update on the pack location. I'm pulling that one down now and will put in a PR there if the problem exists in that version too.

**Comment by userlocalhost** [comment]
Thank you for your correction. It's a bug that I made, sorry.

The boto version that aws-pack uses is fixed to v2.41.0 by the [requirements.txt](https://github.com/StackStorm-Exchange/stackstorm-aws/blob/master/requirements.txt#L2).

And I confirmed that problem and your fix is right.
```
$ /opt/stackstorm/virtualenvs/aws/bin/python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto
>>> boto.__version__
'2.41.0'
>>> from boto import s3
>>> dir(s3)
['RegionInfo', 'S3RegionInfo', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', 'connect_to_region', 'deletemarker', 'get_regions', 'regions', 'user']
>>> s3.bucket
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'bucket'
>>> from boto.s3.bucket import Bucket
>>> type(Bucket)
<type 'type'>
>>> 
```

Thank you.

**Comment by semantic-lee** [comment]
any updates to this ?

**Comment by LindsayHill** [comment]
Addressed on https://github.com/StackStorm-Exchange/stackstorm-aws/pull/4

**Pull request closed without merging**
