### PR TITLE
RFR: Circle CI pack

### PR DESCRIPTION
**Pull request by lakshmi-kannan**
## TODO

*  [x] Tests
 
## Examples

```
/m/s/s/st2 git:purge_models_optimization ❯❯❯ st2 run circle_ci.wait_until_build_finishes project=project=armab/st2-packages build_number=377
..
id: 5668a1f732ed35537681cb8b
status: failed
result:
{
    "result": null,
    "exit_code": 1,
    "stderr": "st2.actions.python.WaitUntilBuildFinishes: INFO     URL: https://circleci.com/api/v1/project/project=armab/st2-packages/377
/mnt/src/storm/st2/virtualenv/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/mnt/src/storm/st2/st2actions/st2actions/runners/python_action_wrapper.py", line 116, in <module>
    obj.run()
  File "/mnt/src/storm/st2/st2actions/st2actions/runners/python_action_wrapper.py", line 61, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/circle_ci/actions/wait_until_build_finishes.py", line 25, in run
    raise Exception(msg)
Exception: Build number 377 for project project=armab/st2-packages not found.
",
    "stdout": ""
}
/m/s/s/st2 git:purge_models_optimization ❯❯❯ st2 run circle_ci.wait_until_build_finishes project=armab/st2-packages build_number=377
..
id: 5668a23c32ed35537681cbdc
status: succeeded
result:
{
    "result": true,
    "exit_code": 0,
    "stderr": "st2.actions.python.WaitUntilBuildFinishes: INFO     URL: https://circleci.com/api/v1/project/armab/st2-packages/377
/mnt/src/storm/st2/virtualenv/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
",
    "stdout": ""
}
/m/s/s/st2 git:purge_models_optimization ❯❯❯

/m/s/s/st2 git:purge_models_optimization ❯❯❯ st2 run circle_ci.get_build_number project=armab/st2-packages vcs_revision=e7fa0eaba03a429fc86aacec59281d63d3076f84
..
id: 5668a02332ed35537681c97e
status: succeeded
result:
{
    "result": 377,
    "exit_code": 0,
    "stderr": "/mnt/src/storm/st2/virtualenv/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
",
```

### CODE REVIEW

**Comment by lakshmi-kannan** [comment]
@Kami: https://github.com/StackStorm/st2contrib/blob/master/Makefile#L99 Is it intentional we don’t install https://github.com/StackStorm/st2contrib/blob/master/requirements-pack-tests.txt in that virtualenv? I added a new dependency and travis is failing. https://travis-ci.org/StackStorm/st2contrib/jobs/97100961.

**Comment by Kami** [comment]
@lakshmi-kannan Yes, all this stuff happens inside the respective script task (e.g. `scripts/pylint-pack.sh, `st2-run-pack-tests`, etc.).

**Comment by Kami** [comment]
Ah, ignore my last comment.

I just noticed you are talking about `requirements-pack-tests.txt` and not pack requirements. In this case the installation of those dependencies happens inside `st2-run-pack-tests` script - https://github.com/StackStorm/st2/blob/master/st2common/bin/st2-run-pack-tests#L33.

It looks like I forgot to remove this file from the repo once we moved run tests script to st2 repo. So please update `st2-run-pack-tests` in st2 repo, remove `requirements-pack-tests.txt` which is not obsolete from this repo and re-run travis build.

**Comment by lakshmi-kannan** [comment]
Well, it looks like pylint target still needs requirements-pack-tests.txt. https://travis-ci.org/StackStorm/st2contrib/jobs/97526671#L326

**Comment by lakshmi-kannan** [comment]
This travis failure makes no sense to me. Those reamaze actions travis is complaining about is not even part of this branch.

**Pull request merged**
