### PR TITLE
Add support for additional AWS services

### PR DESCRIPTION
**Pull request by DoriftoShoes**
This PR adds support for the following AWS services:

- [x] IAM
- [x] VPC
- [x] S3
- [x] CloudFormation
- [x] RDS
- [x] SQS

Known issues:

- [x] parsers need to be fixed

### CODE REVIEW

**Comment by manasdk** [comment]
This better be autogenerated :P

**Comment by DoriftoShoes** [comment]
I wrote ALL of these actions by hand.  It was a labor of love.

**Comment by Kami** [comment]
TL;DR

**Comment by haad** [comment]
+1

**Comment by Kami** [comment]
It looks like this PR broke out ci/cd workflows because it changed some parameter types from integer to string.

```@@ -38,7 +38,7 @@ parameters:
   instance_profile_name:
     type: string
   instance_type:
-    default: t2.medium
+    default: m1.small
     type: string
   kernel_id:
     type: string
@@ -46,10 +46,10 @@ parameters:
     type: string
   max_count:
     default: 1
-    type: integer
+    type: string
   min_count:
     default: 1
-    type: integer
+    type: string
   module_path:
     default: boto.ec2.connection
     immutable: true
```

I'm temporary reverting parameter type change to unblock us.

**Pull request merged**
