### PR TITLE
Brocade VDX

### PR DESCRIPTION
**Pull request by bigmstone**
### Status 
new pack, finished

### Description
Brocade VDX pack for interacting with Brocade NOS devices.

### Checklist
- [x] Metadata: pack.yaml, icon, structure
- [x] Version bump
- [x] Code linting
- [x] Tests

### CODE REVIEW

**Comment by dzimine** [comment]
@bigmstone can you please add any auto-generation tools you use into ./etc here, so that they come together. Like we do in https://github.com/StackStorm/openstack pack.

**Comment by Kami** [comment]
Some ideas for future improvements for the action generator to make the code feel a bit more Pythonic and less auto-generated:

* Use camel case for class names
* Explicitly declare arguments instead of using args

In any case, not a blocker, just something we can improve on in the future.

**Comment by dzimine** [comment]
good by my YOLO look. +1

**Comment by Kami** [comment]
If it works, let's go ahead and merge it :+1: 

We can improve it in the future.

**Pull request merged**
