### PR TITLE
Do not crash Slack sensor if unexpected message

### LINKED ISSUE #175: Slack Sensor Instability
The messages coming through Slack's RTM API seem to be quite varied and may or may not contain certain data. For example, #174 addresses some of the variations in profile data. However, I have also seen some quirkiness with `data` not containing a `channel` key as well (I haven't dug in to find what these messages are yet, but that's weird - maybe private groups?). Here's a stacktrace from such an occurance:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/st2reactor/container/sensor_wrapper.py", line 336, in run
    self._sensor_instance.run()
  File "/usr/lib/python2.7/dist-packages/st2reactor/sensor/base.py", line 92, in run
    self.poll()
  File "/data/st2contrib/packs/slack/sensors/slack_sensor.py", line 45, in poll
    self._handle_result(result=result)
  File "/data/st2contrib/packs/slack/sensors/slack_sensor.py", line 75, in _handle_result
    handler_func(data=item)
  File "/data/st2contrib/packs/slack/sensors/slack_sensor.py", line 87, in _handle_message
    channel_info = self._get_channel_info(channel_id=data['channel'])
  File "/data/st2contrib/packs/slack/sensors/slack_sensor.py", line 122, in _get_channel_info
    channel=channel_id)['channel']
KeyError: 'channel'
```
Note: Line numbers may be off as I was poking around on this file a bit...

Ideally, I would like for the sensor to keep on trucking despite running into issues with a particular message. Would it be appropriate to wrap `self._handle_result(result=result)` in the [poll](https://github.com/StackStorm/st2contrib/blob/master/packs/slack/sensors/slack_sensor.py#L51) function in a `try`/`except` block? On error, it could log the event, but keep the sensor running.

Thoughts?

### PR DESCRIPTION
**Pull request by ryandub**
Closes #175

If the message from Slack is not formatted as expected, log the issue
and continue - do not crash sensor.

### CODE REVIEW

**Comment by Kami** [comment]
Thanks.

For readability reasons, I would prefer to add another method which calls `self._handle_message` and catch the exception there (or something along those lines - decorator would also work).

For example:

```python
...
self._handlers = {
   'message': self._handle_message_ignore_errors,
}
....

def handle_message_ignore_errors(...):
  try:
    self._handle_message(...)
  except:
   ...
```

**Comment by ryandub** [comment]
Thanks @Kami ! I've updated with your suggestion.

**Comment by jfryman** [comment]
Awesome! Thanks so much for the code! :metal:

**Comment by Kami** [comment]
@ryandub Thanks again.

This pull request and changes in #181 should now make sure the sensor doesn't die on non-fatal errors.

**Pull request merged**
