### PR TITLE
[git] enables to specify multiple repositories to monitor commit events (#589)

### PR DESCRIPTION
**Pull request by userlocalhost2000**
### Status
- bugfix
### Description

I expand  to be able to specify multiple repositories to monitor, which is mentioned in #589.

These are the main-points of this change.
- corrects the configuration file which cloud be specified multiple repositories
- adapt sensor processing to handle multiple repositories
- add a 'repository_url' parameter to the trigger parameter
### Checklist (tick everything that applies)
- [x] Metadata: pack.yaml, icon, structure (required for new packs)
- [x] Version bump (required for changed packs)
- [x] Code linting (required, can be done after the PR checks)
- [x] [Tests](https://docs.stackstorm.com/development/pack_testing.html) (not required but really recommended)

### CODE REVIEW

**Comment by userlocalhost2000** [comment]
I wrote a test in accordance with following.
https://docs.stackstorm.com/development/pack_testing.html

Would you please review it?

Thank you.

**Comment by userlocalhost2000** [comment]
I've finished this work. Can you please merge this?

**Comment by Kami** [comment]
@userlocalhost2000 Sorry for the delay, I will look into it as soon as possible.

On a related note - can you please sync this branch with master to resolve the conflict?

**Comment by userlocalhost2000** [comment]
@Kami Thank you for your reply. I corrected the conflict!

**Comment by Kami** [comment]
Thanks - I made two small modifications (2261065dd775ba1a5a3db206649ec8e4eb582f11, 118fc76672492322210b32ce1c694a6d82359026) and merged your changes into master.

Thanks again!

**Pull request merged**
