### PR TITLE
Add "disable_formatting" parameter to the slack.post_message action

### PR DESCRIPTION
**Pull request by Kami**
With this parameter user can disable formatting and parsing of the message.

screenshot from 2015-06-01 16 46 44

### CODE REVIEW

**Comment by jfryman** [comment]
:+1:

**Comment by manasdk** [comment]
Do we get support for this in hubot-stackstorm as well?

**Comment by jfryman** [comment]
@manasdk good question. I think that needs to be there as well.

**Comment by Kami** [comment]
Yes - for that, we need to update hubot-slack adapter and JavaScript slack client.

I have opened PRs against respective the projects. If the PRs won't get merged soon, we will sadly need to resort to forking those projects.

**Comment by jfryman** [comment]
@manasdk actually, I don't think that matters... right as I hit enter. hubot-stackstorm is already receiving the raw end from StackStorm, but the client may still render which is why there is the PR @Kami posted earlier

**Pull request merged**
