### PR TITLE
[WIP] Add Solarwinds Orion pack.

### PR DESCRIPTION
**Pull request by jjm**
### Status 

WIP, creating the PR for visibility, linting checks and comments.

- new pack, work in progress

### Description

Add pack for integrating with the Solarwinds Orion monitoring platform.

### Checklist (tick everything that applies)

- [X] Metadata: pack.yaml, icon, structure (required for new packs)
- [ ] Version bump (required for changed packs)
- [ ] Code linting (required, can be done after the PR checks)
- [ ] Tests (not required but really recommended)
- [ ] Add more actions & alaises.
- [ ] Refactor actions to use lib.

### CODE REVIEW

**Comment by Kami** [comment]
Thanks for the contribution!

I will look into it shortly.

**Comment by BrainMonkey** [comment]
Very interested in this and something can actually contribute to finally.

**Comment by jjm** [comment]
Cool, I'm attempting to come up with the list of actions to include on the initial merge. 

So far I have the following actions:

- ncm_config_download.
- status.
- unmanage_node.
- remanage_node.

And so far planning to look at updating custom properties, adding nodes to NPM & NCM. These ~7 actions seem like a good starting point. So I'll then look at adding more actions & aliases in with additional PRs.

**Comment by BrainMonkey** [comment]
Thats a good start , another awesome feature would be able to check IPAM IP statuses and also set statuses

**Comment by jjm** [comment]
Last time I checked, IPAM did not have much in the way of API hooks. Hopefully this has changed.

There was issues with our fork of the repo, so this has been replaced by PR#466.

**Pull request closed without merging**
