### PR TITLE
added transition issue action

### PR DESCRIPTION
**Pull request by psychopenguin**

### CODE REVIEW

**Comment by emedvedev** [comment]
Don't forget to bump the version in `pack.yaml`.

**Comment by psychopenguin** [comment]
@emedvedev done! :)

**Comment by emedvedev** [comment]
Alright, merging. FYI, enhancing your actions with corresponding aliases gets you a lot of love from everyone at StackStorm. :heart:

**Comment by emedvedev** [comment]
We could really use Jira aliases. Note to self. :)

**Pull request merged**
