### PR TITLE
Add Dimension Data pack

### PR DESCRIPTION
**Pull request by tonybaloney**

### CODE REVIEW

**Comment by manasdk** [comment]
lol ... 100+ files.

**Comment by manasdk** [comment]
Don't see a README. We got some minimum standards around here you know :P

Seriously though would be hard to use this pack without a README. If you plan to add it later thats ok too.

Btw, are all the actions handwritten?

**Comment by tonybaloney** [comment]
here u go @manasdk

**Comment by manasdk** [comment]
LGTM. Will wait on travis and merge

**Comment by emedvedev** [comment]
We currently use 64x64 icon size across all packs, please resize. Might break in contrib README, or webui, or flow (although I guess you'd notice the last two).

**Comment by tonybaloney** [comment]
@emedvedev ok. done

**Pull request merged**
