### PR TITLE
[salt] Hotfix/missing target args

### PR DESCRIPTION
**Pull request by jcockhren**
### Status 

- bugfix

### Description

This bugfix ensures the developer can customize which minons are targeted and how when using [Execution Module Actions](https://github.com/StackStorm/st2contrib/tree/master/packs/salt#execution-module-actions)

### Checklist (tick everything that applies)

- [ ] Metadata: pack.yaml, icon, structure (required for new packs)
- [x] Version bump (required for changed packs)
- [x] Code linting (required, can be done after the PR checks)
- [ ] Tests (not required but really recommended)

### CODE REVIEW

**Comment by Kami** [comment]
Thanks for the contribution.

Just curious - was this argument added to ansible in one of the recent versions?

**Comment by Kami** [comment]
It looks like salt calls parameter `tgt` for some reason.

Was there some reason why you used `target` instead of `tgt`? Using `tgt` might make more sense if it keeps it consistent with the Salt parameter names.

**Comment by jcockhren** [comment]
@Kami yeah, that was on purpose. I wanted to use `target` since it's clearer.

**Comment by Kami** [comment]
Alright, as long as this is obvious to the user I'm fine with that.

**Pull request merged**
