### PR TITLE
Reamaze conversations

### PR DESCRIPTION
**Pull request by jfryman**
This PR adds the ability to search through re:amaze conversations in an action.

### CODE REVIEW

**Comment by Kami** [comment]
:+1:

**Comment by Kami** [comment]
Hm, checks don't seem OK - need to dig in why git-changes stuff didn't work correctly (it didn't detect any changes, but it works fine locally).

**Comment by Kami** [comment]
I think I found the issue. It turns out `git-changes-*` scripts never worked on Travis.

Travis performs a shallow clone of a single branch which means we can't directly compare to master because master branch / ref is not available locally. I believe this should fix it - https://github.com/StackStorm/st2contrib/commit/5bd2ded50db004a9b79bf6b50e53632deada73ef

**Comment by jfryman** [comment]
@Kami good deal. Thanks for the fix! :heart:

**Pull request merged**
