### PR TITLE
Update st2 pack to employ new chatops features

### PR DESCRIPTION
**Pull request by enykeev**
screen shot 2015-12-02 at 7 23 51 pm

### CODE REVIEW

**Comment by enykeev** [comment]
There's two major problems I've faced during this PR:
* the `{{ trigger }}` returned by `core.st2.generic.notifytrigger` may by itself include jinja templates which would then end up trying to be resolved by st2action and in some cases would result in the whole execution failing due to absence of required context variables
* `st2.execution_list` creates an execution that includes another N previous executions into itself. Really not hard to imagine what would happen if you try to run in multiple times in succession. For those lacking imagination:

  ```
command document too large
  File \"/usr/lib/python2.7/dist-packages/st2actions/worker.py\", line 113, in _run_action
    result = self.container.dispatch(liveaction_db)
  File \"/usr/lib/python2.7/dist-packages/st2actions/container/base.py\", line 83, in dispatch
    else self._do_run(runner, runnertype_db, action_db, liveaction_db))
  File \"/usr/lib/python2.7/dist-packages/st2actions/container/base.py\", line 138, in _do_run
    result, context)
  File \"/usr/lib/python2.7/dist-packages/st2actions/container/base.py\", line 206, in _update_live_action_db
    liveaction_db=liveaction_db)
  File \"/usr/lib/python2.7/dist-packages/st2common/util/action_db.py\", line 196, in update_liveaction_status
    liveaction_db = LiveAction.add_or_update(liveaction_db)
  File \"/usr/lib/python2.7/dist-packages/st2common/persistence/base.py\", line 155, in add_or_update
    model_object = cls._get_impl().add_or_update(model_object)
  File \"/usr/lib/python2.7/dist-packages/st2common/models/db/__init__.py\", line 174, in add_or_update
    instance.save()
  File \"/usr/local/lib/python2.7/dist-packages/mongoengine/document.py\", line 267, in save
    upsert=True, **write_concern)
  File \"/usr/local/lib/python2.7/dist-packages/pymongo/collection.py\", line 750, in update
    docs, check_keys, self.uuid_subtype, client)
```

**Comment by jfryman** [comment]
Just to cross-post and provide context here...

A good pattern in ChatOps if the data is unsafe, authenticated, or otherwise too verbose... is to give a minimal amount of information and/or a weblink to get a user to where they need to be. Having access in the context of chat to quickly navigate around is the objective here.

In the specific case here. Would maybe a link to the WebUI be sufficient to meet the above criteria?

**Comment by enykeev** [comment]
screen shot 2015-12-18 at 7 31 26 pm

**Comment by armab** [comment]
Oh, that's possible?
Really nice examples ^^

**Comment by enykeev** [comment]
yeah, now when we solved double rendering, there's really quite a lot of stuff we can do with chatops

**Comment by jfryman** [comment]
YES!!!! :heart:

**Comment by emedvedev** [comment]
Anyone against merging this? I'm pretty sure it's safe now since every new install will come with the new chatops, and old installs already have the pack. Also, long due!

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1455170538006813

**Comment by emedvedev** [comment]
Extended the PR a bit, brought execution lists back (we need to do something with `execution_list`, I filed an issue, but it's outside the scope of this PR). Merging.

There's a Travis failure unrelated to the PR:
```
Command "/home/travis/build/StackStorm/st2contrib/virtualenv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-UaL4Oq/wit/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-u3RaSE-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/travis/build/StackStorm/st2contrib/virtualenv/include/site/python2.7/wit" failed with error code 1 in /tmp/pip-build-UaL4Oq/wit
```

**Pull request merged**
