### PR TITLE
Resize Twilio Icon

### PR DESCRIPTION
**Pull request by armab**
Resize it to normal `64px`, so it doesn't break the main README view:

### CODE REVIEW

**Comment by Kami** [comment]
Hm, interesting enough, all the icons displayed in the README here are of the same size.

selection_231

**Comment by armab** [comment]
Just checked in different browsers.

FF and IE - not resized (my screenshot)
Chrome - automatically scaled (your screenshot)

**Comment by Kami** [comment]
Yeah, I just had a look and it looks pretty awful in Firefox.

**Comment by Kami** [comment]
Merged, thanks.

**Pull request merged**
